site_name: About My Car
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: docs
nav:
  - Home: index.md
  - Arc42: arc42.md
  - ADRs:
      - Datenbank: adrs/database-adr.md
      - Techstack: adrs/techstack-adr.md
