@startuml verteilung
node "Browser" {
    component "Frontend (React)" as frontend
}

node "Docker-Compose" {
    node "nginx (Container)" as nginx {
        component "nginx" as nginx_comp
    }
    node "Backend (Container)" as backend {
        component "Backend (Node.js)" as backend_comp
    }
    node "Datenbank (Container)" as database {
        component "Datenbank (PostgreSQL)" as database_comp
    }
    
}

node "Externe API" {
        component "Wetter-API (open-meteo)" as weather_api
    }

frontend -right-> nginx_comp : HTTP Request
nginx_comp --> backend_comp : API Request
backend_comp --> database_comp : SQL Query
backend_comp -left-> weather_api : HTTP Request
@enduml