name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install FE dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./src/frontend

      - name: Run Jest coverage for FE
        run: yarn test --coverage
        working-directory: ./src/frontend

      - name: Install BE dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./src/backend

      - name: Run Jest coverage for BE
        run: yarn test --coverage
        working-directory: ./src/backend

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}